# Generated by Django 5.2.1 on 2025-06-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_selfinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
