# Generated by Django 5.2.1 on 2025-06-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_selfinfo_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='selfinfo',
            name='email',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selfinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selfinfo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='pcs_type',
            field=models.CharField(choices=[('val', 'val'), ('vnt', 'Vnt')], max_length=3),
        ),
        migrations.AlterField(
            model_name='selfinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
