# Generated by Django 5.2.1 on 2025-07-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_selfinfo_name_selfinfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='serija',
            field=models.CharField(choices=[('AA', 'AA'), ('VSP', 'VSP')], default='AA', max_length=3),
        ),
    ]
