# Generated by Django 5.2.7 on 2025-11-02 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_serija'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='selfinfo',
            name='activity_start_date',
            field=models.DateField(blank=True, help_text='Individualios veiklos pradžios data (VSDI lengvatai)', null=True),
        ),
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_30_percent_rule', models.BooleanField(default=True, help_text='Naudoti 30% išlaidų taisyklę')),
                ('actual_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Faktinės išlaidos (jei nenaudojama 30% taisyklė)', max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
